from __future__ import annotations
import math
from pathlib import Path
from argus7.design.geometry import (
    derive_wing, derive_booms, derive_tail_panel, wing_le_x,
)
from argus7.cad.model import section_stations, _section_coords


def _poly(coords) -> str:
    return ", ".join(f"[{x:.5f},{y:.5f}]" for x, y in coords)


def emit_openscad(design, path: str | Path) -> Path:
    """Emit a viewable .scad whose header and geometry both come from the
    loaded design. Nothing here is hand-typed, which is what Defect 2 was:
    a hand-typed header once claimed a MAC that disagreed with the file's
    own geometry AND with the report.

    RULING P5: section() draws the airfoil in the XY plane and extrudes
    along Z, then rotates the whole slab 90deg about X before translating
    into place, so hulling consecutive stations sweeps spanwise (in Y) --
    verified empirically to render with span in Y and chord in X.

    RULING P16: boom and fuselage geometry come from derive_booms() and
    design.fuselage.stations respectively, not from a deleted
    design.booms.length_m field or hardcoded fuselage fractions.

    RULING P17: the inverted-V tail is emitted too, at the same station
    build_tail (argus7.cad.model) places it, so this file depicts the same
    aircraft the STEP/STL do.
    """
    g = derive_wing(design.wing)
    bg = derive_booms(design)

    wing_coords = _section_coords(design.wing.airfoil)
    tail_coords = _section_coords(design.tail.airfoil)

    # ---- tail panel geometry, SHARED with argus7.cad.model.build_tail ----
    # FINAL REVIEW I5: this block used to re-derive panel_area, panel_span,
    # c_root, mac and x_le itself, "mirrored from build_tail" by comment
    # only. Both paths now read the one derivation.
    tp = derive_tail_panel(design)

    lines = [
        "// ==== GENERATED FILE - DO NOT EDIT ====",
        f"// Generated by argus7.cad.to_openscad from design '{design.name}' "
        f"variant {design.variant}.",
        "// Edit design/*.yaml and regenerate. Hand-editing reintroduces the",
        "// geometry-drift defect this pipeline exists to prevent.",
        f"// S = {g.area_m2:.4f} m2 | AR = {g.aspect_ratio:.4f} | b = {g.span_m:.4f} m",
        f"// c_root = {g.chord_root_m:.4f} m | c_tip = {g.chord_tip_m:.4f} m "
        f"| MAC = {g.mac_m:.4f} m",
        f"// tail: c_root = {tp.c_root_m:.4f} m | c_tip = {tp.c_tip_m:.4f} m "
        f"| MAC = {tp.mac_m:.4f} m",
        f"// booms: x_fwd = {bg.x_fwd:.4f} m | x_aft = {bg.x_aft:.4f} m "
        f"| y_station = {bg.y_station_m:.4f} m",
        "// Axes: x aft, y starboard, z up.",
        "$fn = 64;",
        f"airfoil = [{_poly(wing_coords)}];",
        f"airfoil_tail = [{_poly(tail_coords)}];",
        "",
        "// RULING P5: draw the airfoil in the local XY plane, extrude a thin",
        "// slab along local Z, then rotate the slab 90deg about X before",
        "// translating into place. That maps the extrusion axis into world Y",
        "// (span), not world Z -- verified to render span-in-Y, chord-in-X.",
        "module section(chord, twist, x_le, y, z) {",
        "    translate([x_le, y, z]) rotate([90,0,0]) linear_extrude(0.001)",
        "        rotate([0,0,twist]) polygon(points=[for (p = airfoil) [p[0]*chord, p[1]*chord]]);",
        "}",
        "",
        "module tail_section(chord, twist, x_le, y, z) {",
        "    translate([x_le, y, z]) rotate([90,0,0]) linear_extrude(0.001)",
        "        rotate([0,0,twist]) polygon(points=[for (p = airfoil_tail) [p[0]*chord, p[1]*chord]]);",
        "}",
        "",
        "module wing() {",
    ]
    stations = section_stations(design, 15)
    dih = math.radians(design.wing.dihedral_deg)
    for (y0, c0, t0, x0), (y1, c1, t1, x1) in zip(stations, stations[1:]):
        z0, z1 = y0 * math.tan(dih), y1 * math.tan(dih)
        # FIX ROUND 1, FINDING 1: OpenSCAD's rotate([0,0,twist]) is a CCW
        # rotation in its local XY plane, the opposite sense from
        # argus7.cad.airfoil_coords.scale_airfoil's own convention
        # (xr = xc*ct + zc*st; zr = -xc*st + zc*ct, chosen in RULING P4
        # specifically so negative twist means washout -- TE rises above
        # LE). Emitting the raw angle here reproduced that same sign bug a
        # second time: TE dropped for washout instead of rising. Negate the
        # angle on the way out so the emitted geometry matches
        # scale_airfoil's washout convention, not OpenSCAD's native sense.
        for sgn in (1, -1):
            lines.append(
                f"    hull() {{ section({c0:.5f}, {-math.degrees(t0):.4f}, {x0:.5f}, "
                f"{sgn * y0:.5f}, {z0:.5f});"
                f" section({c1:.5f}, {-math.degrees(t1):.4f}, {x1:.5f}, "
                f"{sgn * y1:.5f}, {z1:.5f}); }}")

    lines += [
        "}",
        "",
        "// RULING P16: fuselage stations come from design.fuselage.stations",
        "// (nose-to-tail (x_frac, r_frac) pairs), not hardcoded fractions.",
        "module fuselage() {",
    ]
    # FIX ROUND 1, FINDING 4: hull() of two spheres bulges past each
    # station by the sphere's own radius along every axis, including x --
    # the real build123d loft (build_fuselage) is a solid of revolution
    # that terminates exactly at each station. A thin disc (radius r,
    # negligible thickness, face normal along x) hulled between stations
    # gives a frustum chain that lands on the stations themselves instead
    # of overshooting them, matching build_fuselage far more closely.
    L, R = design.fuselage.length_m, design.fuselage.max_diameter_m / 2.0
    fus_stations = [(xf * L, max(rf * R, 1e-3)) for xf, rf in design.fuselage.stations]
    for (x0, r0), (x1, r1) in zip(fus_stations, fus_stations[1:]):
        lines.append(
            f"    hull() {{ translate([{x0:.5f},0,0]) rotate([0,90,0]) "
            f"cylinder(r={r0:.5f}, h=0.001);"
            f" translate([{x1:.5f},0,0]) rotate([0,90,0]) "
            f"cylinder(r={r1:.5f}, h=0.001); }}")
    lines += [
        "}",
        "",
        "// RULING P16: length and position come from derive_booms(design),",
        "// not the deleted design.booms.length_m field.",
        "module booms() {",
        f"    for (s = [1,-1]) translate([{(bg.x_fwd + bg.x_aft) / 2:.5f}, "
        f"s*{bg.y_station_m:.5f}, 0]) rotate([0,90,0]) "
        f"cylinder(d={design.booms.diameter_m:.5f}, h={bg.length_m:.5f}, center=true);",
        "}",
        "",
        "// RULING P17: inverted-V tail, at the station build_tail",
        "// (argus7.cad.model) places it -- the viewer must show the same",
        "// aircraft the STEP/STL do.",
        "module tail() {",
        "    for (s = [1,-1]) hull() {",
        f"        tail_section({tp.c_root_m:.5f}, 0, {tp.x_le_m:.5f}, s*{bg.y_station_m:.5f}, 0);",
        f"        tail_section({tp.c_tip_m:.5f}, 0, {tp.x_le_m:.5f}, "
        f"s*{bg.y_station_m + tp.y_tip_offset_m:.5f}, {tp.z_tip_offset_m:.5f});",
        "    }",
        "}",
        "",
        f"translate([{wing_le_x(design):.5f}, 0, "
        f"{design.wing.z_offset_m:.5f}]) wing();  "
        "// z from design.wing.z_offset_m -- FINAL REVIEW C1: this was a "
        "second hand-typed copy of build_aircraft's 0.05 wing z-lift",
        "fuselage();",
        "booms();",
        "tail();",
    ]
    p = Path(path)
    p.write_text("\n".join(lines) + "\n")
    return p
